#!/bin/bash

set -ev
# Only build docker containers if we pass the build docker var, if it's a cron job (nightly builds), or in an enterprise branch
if [ ! -z "${BUILD_DOCKER}" ] ||
    [ "${TRAVIS_EVENT_TYPE}" = "cron" ] ||
    [[ "${TRAVIS_BRANCH}" =~ ^enterprise ]]; then
    app_name="hub"
    local_image="travishub_$app_name" # Docker Compose removes dashes and expects the name to end with the build app name
    quay_image=quay.io/travisci/travis-hub;

    docker-compose build --build-arg bundle_gems__contribsys__com="$BUNDLE_GEMS__CONTRIBSYS__COM" "$app_name";
    docker login -u="$QUAY_ROBOT_HANDLE" -p="$QUAY_ROBOT_TOKEN" quay.io;
    docker images;

    docker tag "$local_image" "$quay_image:$TRAVIS_BRANCH";
    docker push "$quay_image:$TRAVIS_BRANCH";

    docker tag "$local_image" "$quay_image:${TRAVIS_COMMIT:0:7}";
    docker push "$quay_image:${TRAVIS_COMMIT:0:7}";

    if [ "${TRAVIS_BRANCH}" = "master" ]; then
      docker tag "$local_image" "$quay_image:latest";
      docker push "$quay_image:$TRAVIS_BRANCH";
    fi
fi

exit 0;
