#!/bin/sh

APPDIR=`pwd`

echo "REPO      : $REPO"

if [ -z "$REPO" ]
then
    REPO="$APPDIR"/.m2/repository
fi

export CLASSPATH=$CLASSPATH_PREFIX:$APPDIR/etc:$REPO/org/jruby/jruby-complete/1.6.5/jruby-complete-1.6.5.jar
export GEM_HOME=$APPDIR/vendor/bundle
export GEM_PATH=$APPDIR/.gems:$APPDIR/vendor/bundle
export PATH=$APPDIR/.gems/bin:$APPDIR/vendor/bundle/bin:$PATH
export BUNDLE_GEMFILE=$APPDIR/Jemfile
export JRUBY_OPTS=--1.9
unset GIT_DIR

echo "APPDIR      : $APPDIR"
echo "REPO        : $REPO"
echo "CLASSPATH   : $CLASSPATH"
echo "GEM_PATH    : $GEM_PATH"
echo "PATH        : $PATH"
# echo "bundler_env : $bundler_env"

max_mem=500m
max_stack=2048k

java $JAVA_OPTS                                             \
  -Dfile.encoding=UTF-8 -Xmx$max_mem -Xss$max_stack         \
  -Djruby.memory.max=$max_mem -Djruby.stack.max=$max_stack  \
  -Dsun.java.command=org.jruby.Main                         \
  -Djruby.compat.version=1.9                                \
  -classpath "$CLASSPATH"                                   \
  -Dbasedir="$APPDIR"                                       \
  org.jruby.Main                                            \
  "$@"
