#!/bin/sh

APPDIR=`pwd`
JRUBY_VERSION="1.6.5"

export CLASSPATH=$CLASSPATH_PREFIX:$APPDIR/etc
export GEM_HOME=$APPDIR/vendor/bundle
export GEM_PATH=$APPDIR/.gems:$APPDIR/vendor/bundle
export PATH=$APPDIR/.gems/bin:$APPDIR/vendor/bundle/bin:$PATH
export BUNDLE_GEMFILE=$APPDIR/Jemfile
#export JRUBY_OPTS=--1.9

# Download a JRuby if needed
if [ ! -d jruby-${JRUBY_VERSION} ]; then
  curl -o jruby-bin-${JRUBY_VERSION}.tar.gz "http://jruby.org.s3.amazonaws.com/downloads/${JRUBY_VERSION}/jruby-bin-${JRUBY_VERSION}.tar.gz"
  tar -xzf jruby-bin-${JRUBY_VERSION}.tar.gz
  rm jruby-bin-${JRUBY_VERSION}.tar.gz
fi

# Add JRuby to the path
export PATH=${APPDIR}/jruby-${JRUBY_VERSION}/bin:$PATH

# Install Bundler if needed
if ! jruby -S gem list | grep bundler > /dev/null; then
  jruby -S gem install bundler --pre --no-ri --no-rdoc --install-dir .gems
fi

# Install gems
bundle install --gemfile=Jemfile

max_mem=500m
max_stack=2048k

# echo "ls .gems/bin"
# echo `ls .gems/bin`
# echo "ls .gems/gems"
# echo `ls .gems/gems`
# echo "ls vendor/bundle/bin"
# echo `ls vendor/bundle/bin`
# echo "ls vendor/bundle/gems"
# echo `ls vendor/bundle/gems`
# echo "env"
# echo `env`
# echo `cat .bundle/config`

jruby                                                           \
  -J-Dfile.encoding=UTF-8 -J-Xmx$max_mem -J-Xss$max_stack       \
  -J-Djruby.memory.max=$max_mem -J-Djruby.stack.max=$max_stack  \
  -J-Dsun.java.command=org.jruby.Main                           \
  -J-classpath "$CLASSPATH"                                     \
  -J-Dbasedir="$APPDIR"                                         \
  "$@"
